### ISSUE TITLE
5ET-954 Remove the Psionics tab from the Front Page

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#1129]
Information
The Psionics page is for a UA class that's been discontinued long ago, and no one ever even uses. It's already been regarded as unfixable by WotC, so keeping up a whole tab on the front page for something that no one ever uses feels redundant.

Who would use it?
It isn't used by anyone, so it would be nice to clean it up.

How would it work?
You can remove the button on the Front Page. If anyone wants to look up the options, they can use the universal search function to find it, just like you would for a large number of the hidden tables and lists.

Why should this be added?
There's technically no reason to do this, but I believe the front page would be nicer with a different tab being there, or it just not being there at all.

- Blubber Nibble#8845

> Upvote - spap#9812

> Downvote - Thomaster#8129

> Upvote - Shilques#8027

> Downvote - deraviin#9963

> Upvote - Reaversfall#5391

> Upvote - Danbog#2054

> Upvote - hackermarx#1857

> Note - spap#9812
> 
> Replacement ideas: Stat Generator, Other Character Creation Options, Languages, Names

> Upvote - JCT#2339

> Indifferent - jkat718#2993

> Upvote - FungusAmongUs#7561

> Upvote - Indy Techwisp#1442

> Upvote - Supertoto#3740

> Upvote - chazlander#6356

> Upvote - CurlyParmesan#2435

> Indifferent - revilowaldow#0001

> Upvote - dutchwhofian#7810

> Upvote - Sword#5282

> Downvote - Simpatico#1943

> Upvote - Jake#2672

> Upvote - Thandul#0087

> Note - Lxran#2292
> 
> (message courtesy of <@!811065834285039621> consider defining icons for most of the features. - missing ones;  Languages | Tables |  Character sheet (when/if  completed) |  Cults |  Objects |  Traps |  Maps |  Recipes |  Conditions |  Deities |  Supernatural Gifts |  Vehicles |  Blacklist |  **Homebrew Builder** |  **Homebrew Manager |  Changelogs

> Indifferent - Lxran#2292

> Note - Lxran#2292
> 
> A small addition: If the button is replaced, a new icon will need to be found. I'm sure Font Awesome already has a suitable one though.

> Upvote - lalo619#1704

> Note - Indy Techwisp#1442
> 
> The current "brain" icon we have could possibly be repurposed for the "Supernatural Gifts" tab.

> Upvote - isaac#9000

> Upvote - Ross#5590

> Upvote - marshall#5180

> Upvote - ATGoldV#2120

> Upvote - Çınar#4540

> Upvote - Chyson#6667

> Indifferent - trrydms#1682

> Upvote - Fabio the Fabiolous#1477

> Upvote - Blubber Nibble#8845

> Upvote - AulesHand#3617

> Downvote - TradeInCaden#5558

> Upvote - 193107008415727617

> Downvote - Rime#1956

> Note - Jake#2672
> 
> Maybe this could be replaced with a search button? Like the one under utilities. That search is so useful and I always forget it's there

> Upvote - TestudoSum#0693

> Upvote - Zach Drac#4297

> Upvote - Swirly D#7443

> Upvote - Georgi#1491

> Indifferent - Uelman#1630

> Upvote - Equinox (╭ರ_•́)#0001

> Downvote - PiXeL71200#5121

> Upvote - Allffo#0001

> Upvote - ineedscissors#9185

> Upvote - 矢澤にこ#7439

> Indifferent - r4z0r#1203

> Upvote - Teccam#1884

> Upvote - m80hg20059#4103

> Upvote - SOME#9917

> Downvote - blackbirdsr#6688

> Upvote - CrackJackFlood#6169

> Upvote - J05H#0003

> Downvote - Roni#6397

> Upvote - HisCursedness#8220

> Upvote - Lasso of Truth#0427

> Upvote - ScandisaurusRex#5240

> Upvote - Erikku Blade#6454

> Upvote - Naxum#8053

> Upvote - Frodos#0129

> Upvote - Nemesius#9310

> Upvote - CT#5218

> Downvote - Thorium#2815

> Upvote - Raven Knight#6754

> Downvote - Eldarch Drykon#2437

> Upvote - Rawmeat#6011

> Upvote - Kael#2097

> Downvote - JarvisBHead#1278

> Upvote - CaptainJet#7684

> Upvote - hudco#0001

> Upvote - Harry Hellscream#8511

> Upvote - Accullius#6475

> Upvote - PaperPrince#6245

> Upvote - 𝓟𝓻𝓲𝓷𝓬𝓮𝓼𝓼 𝓔𝓵𝓲𝓼𝓮 🍳#8978

> Upvote - Hiiden#3634

> Upvote - Demunoki#6867

> Upvote - Weisz#8008

> Upvote - Jackson4499#6355

> Downvote - Naryxian#0001

> Indifferent - TequilaIcarus#2784

> Upvote - 2307#8629

> Downvote - Last_Username#4431

> Upvote - Cyber Stephen#2758

> Upvote - omegazman#6491

> Upvote - Гейб#3100

> Upvote - Martii-Wizard, DM, General Pain#9942

> Downvote - Stanisgrox#0543

> Downvote - 4535992#1766

> Upvote - ZhoukenTaishin#5883

> Indifferent - Anase Skyrider#0563

> Upvote - A Dirty Ewok#3586

> Downvote - ΦωΦ#9506

> Upvote - The True Eevee#7642

> Upvote - Iserlohn#1174

> Upvote - Eldrazi Elk#8264

> Upvote - Jaxis#7693

> Indifferent - Henry F. Dewey#5696

> Downvote - Tim-Hogan#9379

> Upvote - Mothben#4456

> Upvote - Valtsu0#4614

> Upvote - Sparksen#2656

Votes: +74 / -17 / ±9

**Comment by crawltracker** [comment]
Note - Lxran#2292

(message courtesy of <@!811065834285039621> consider defining icons for most of the features. - missing ones;  Languages | Tables |  Character sheet (when/if  completed) |  Cults |  Objects |  Traps |  Maps |  Recipes |  Conditions |  Deities |  Supernatural Gifts |  Vehicles |  Blacklist |  **Homebrew Builder** |  **Homebrew Manager |  Changelogs

**Comment by crawltracker** [comment]
Note - Lxran#2292

A small addition: If the button is replaced, a new icon will need to be found. I'm sure Font Awesome already has a suitable one though.

**Comment by crawltracker** [comment]
Note - Indy Techwisp#1442

The current "brain" icon we have could possibly be repurposed for the "Supernatural Gifts" tab.

**Comment by SnortsAlot** [comment]
@gobemouche 's full NOTES consider defining icons for most of the features.
- missing ones; 
Languages
Tables
Character sheet (when/if  completed)
Cults
Objects
Traps
Maps
Recipes
Deities
Supernatural Gifts
Vehicles
Blacklist
Homebrew Builder
Homebrew Manager
Changelogs
 
And allow the user to decide which 16 to use.

Default to the current list - or perhaps have someone do a poll for which are the most popular features and list them on the front page as the defaults.

**Comment by crawltracker** [comment]
Note - Jake#2672

Maybe this could be replaced with a search button? Like the one under utilities. That search is so useful and I always forget it's there

**Comment by crawltracker** [comment]
Note - Giddy#0001

Resolved - Implemented for next release
