### ISSUE TITLE
5ET-1029 "Imposes [X] saving throw/ability check" filter for bestiary

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#1171]
Information
A filter for each type of saving throw in the bestiary. Not the saving throws with which the creatures are proficient, but those that they force on players. 

For example: i want dragons with a breath weapon without DEX save, or with exclusively STR and CON saves. 

In the moment the only work around is to text search "constitution saving throw", but it's not as flexible as having the actual filter, and it wouldn't work for the instances where it gives you the option to "must make a strength or dexterity saving throw (their choice)" blablabla.

Same thing for when a creature imposes an ability check (such as those that prone or eat PCs)

Who would use it?
DMs that want to find specific combinations of creatures

How would it work?
It's a filter

Why should this be added?
It just makes sense it exists, and it's useful

- Teccam#1884

> Indifferent - spap#9812

> Upvote - Teccam#1884

> Upvote - boustrophedonLanguage#8008

> Indifferent - modnar#9949

> Upvote - Reaversfall#5391

> Upvote - Jagteshwar#7636

> Indifferent - Uelman#1630

> Upvote - Rolazzo#1715

> Upvote - addtheletters#8350

> Downvote - Shadowspawn#7582

> Upvote - JCT#2339

> Upvote - Pip#7676

> Upvote - DM Keith#2042

> Upvote - CrackJackFlood#6169

> Upvote - Umbreeunix#6904

> Upvote - ineedscissors#9185

> Upvote - Coquinou#9054

> Upvote - Georgi#1491

> Upvote - Thomaster#8129

> Upvote - Jackson4499#6355

> Upvote - Cora#8878

> Upvote - DatThaiGuyReef#8159

> Upvote - lobo#1081

> Upvote - Xecron#4993

> Upvote - Nyx.Na#3321

> Upvote - Ejkesler#1022

> Upvote - Cujo#0539

> Upvote - CallMeCal [they/them]#9137

> Upvote - Penndragon#9538

> Upvote - craig.m#3790

> Upvote - Kurrgan#1337

> Upvote - why_not#9352

> Upvote - Blue64#2412

> Upvote - Moonbeam#6479

> Upvote - Deastrumquodvicis#7737

Votes: +31 / -1 / ±3

**Comment by bruno-71** [comment]
I think I could add this filter to the Bestiary (similar to the "conditionInflict" tags/filter).  But how do the JSON files get populated with new data?  A new tag type would need to be created.  How is this usually handled?

**Comment by crawltracker** [comment]
Note - giddy_#0

Resolved - Merged into 5ET-924 (5etools/tracker#1104)
