### ISSUE TITLE
5ET-073 Reorganize Sidekicks to match UASIK

### ISSUE THREAD

**Issue by 5ecrawlreporter** [5etools/tracker#173]
**Feature Request:** Reorganize Sidekicks to match UASIK

**Extra Information** The sidekick rules from the Dragon of Icespire Peak have an existing Unearthed Arcana counterpart: UA: Sidekicks. The new rules should probably match how the existing ones are presented.
**Who would use it?** Users looking for Sidekick rules.
**How would it work?** Sidekick rules should be added to the VARIANT/OPTIONAL RULES PAGE and Sidekick classes/subclasses and levels info should be added to the CLASSES page.
**Why should this be added?** Consistency and improved presentation of information.

- FedoraMark#4407

> Upvote - DestinedLight (рурик)#8275

> Upvote - Dante ÔωÔ#8008

> Upvote - Danbog#0001

> Upvote - Modnar#2707

> Upvote - FedoraMark#4407

Votes: +5 / -0

**Comment by TheGiddyLimit** [comment]
The rules have been added to the Variant/Optional page for next release, but the classes don't have enough similarities with regular classes to afford including them in the classes page.
