### ISSUE TITLE
5ET-075 Clickable extend to new DM Screen box

### ISSUE THREAD

**Issue by 5ecrawlreporter** [5etools/tracker#174]
**Feature Request:** Clickable extend to new DM Screen box.

**Who would use it?**  People with touchscreen solutions. It now moves the screen for some stupid ass reason.
**How would it work?** Instead of the drag to extend solution we have now, also have a click to extend option. So instead of dragging, you click to make it 2 columns, or 2 rows
**Why should this be added?** Help touch screen users. (this would technically also help mobile users.)

- LordDusk#0001

> Upvote - Modnar#2707

> Upvote - badooga#8108

Votes: +2 / -0

**Comment by TheGiddyLimit** [comment]
Implemented for next release.
