### ISSUE TITLE
5ET-161 SRD compliant filter

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#266]
**Feature Request:** SRD compliant filter

**Who would use it?** Good moral upstanding folks, looking to build from scratch
**How would it work?** Add a tag for SRD, all things native to SRD get it, if SRD is setup only SRD is displayed - maybe include that in the js/utils.js like for homebrew auto ad so that people can limit what is viewed?
**Why should this be added?** Silverbass/SRD compliance.

- Modnar#2707

> Upvote - Sulandir#0001

> Upvote - LordDusk#0001

> Upvote - boustrophedonLanguage#8008

> Upvote - mewdli#6837

> Upvote - badooga#8108

> Upvote - Metacomet10#3669

> Upvote - PointOfViewMan#5718

> Upvote - Roxy#8008

> Upvote - DestinedLight (рурик)#8275

> Upvote - BlackAceXIII#3976

> Upvote - Gathis#6628

> Upvote - MrVizious#4542

> Downvote - Arth#2710

> Upvote - Zogs99#0773

> Upvote - Conorayne#2880

> Upvote - Danbog#0001

> Upvote - Modnar#2707

> Upvote - Rnar#9417

> Upvote - Makke#8524

> Upvote - abbott#2506

> Upvote - Aaron Kannon#7061

> Upvote - Iacentis#6845

> Upvote - Konahrik13#3572

> Upvote - DefaultSimon#5072

Votes: +23 / -1

**Comment by DMsGuild201** [comment]
Might be good to have SRD.5e.tools site that features only SRD default content.

**Comment by crawltracker** [comment]
Note - Giddy#0001

Resolved - Added for next release.
