### ISSUE TITLE
5ET-286 The ability to locally save and load "preset" filter selections

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#353]
**Feature Request:** The ability to locally save and load "preset" filter selections.

**Extra Information**
**Who would use it?** People who play in several campaigns with different specific restrictions on content.
**How would it work?** At the top of the Filter window, press a button that says "Add Presets".  This displays a Save button for any filter subsections that have been changed from the default, as well as the top level row.  Pressing "save" stores the current values locally and adds a numbered button for each saved preset.  Pressing the "Add Presets" button again toggles off the saving mode.  Pressing the numbered buttons would load the saved preset values.
**Why should this be added?** Would save time when looking for various specific things within a greater pool of content.  Being able to load back to a Preset would prevent someone from having to click All or Default and then editing back to their personally used options each time.
**Example:**

> Upvote - 191956661156577280

> Upvote - MrVauxs#8622

> Upvote - spap#9812

> Note - 191956661156577280
> 
> Alternate implementations - 1: Named presets instead of just numbers. 2: Using a dropdown menu instead of buttons for loading presets. 3: Just the ability to "Save to Default", overwriting the current Defaults.

> Downvote - Gathis#6628

> Upvote - GoR#9388

> Upvote - EliasofPi#9987

> Upvote - Aevilok 🎃#6979

> Upvote - �🔼#0497

> Upvote - Modnar#2707

> Upvote - Can Dinçer#3899

> Upvote - PyroPhoenix#2370

> Upvote - 151096097840824320

> Upvote - Cat#9597

> Upvote - MrVizious#4542

> Downvote - SigilBlue#6700

> Upvote - FedoraMark#4407

> Upvote - 247448810106650624

> Upvote - Mike#3362

> Upvote - Zilent-Noize#9196

> Upvote - HaLwAsA#5109

> Upvote - joshjosh100#2597

> Upvote - Wemo#2728

> Upvote - Nekro "Shapiro" Philadelphia#2491

> Upvote - Alex Pendragon#6747

> Upvote - Adriannom#0237

Votes: +23 / -2 / ±0

**Comment by TheTooSlowSloth** [comment]
I personally think this should be the next feature added to the 5etools search mechanics. The filters are great, but its extremely difficult to set up different filters for different games every time. I don't remember what all the UA documents are by name, and when you start introducing homebrew it gets even more confusing.

**Comment by crawltracker** [comment]
Note - giddy_ (Giddy)

Resolved - Implemented
