### ISSUE TITLE
PLUT-19 Play Youtube Audio in Foundry

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#389]
Feature Request: Play Youtube Audio in Foundry

Who would use it? Gamemaster/Trusted users (access control option?)
How would it work? 
1) Copy/Paste youtube link in to field
2) Foundry player plays the audio track or plutonium downloads mp3 to foundry then foundry plays the track
Why should this be added? Cuts down a lot on the process of importing music on the fly.

- Puggahz#7654

> Upvote - boustrophedonLanguage#8008

> Upvote - Darien Todbringer#0992

> Upvote - SigilBlue#6700

> Upvote - Legend#9861

> Upvote - ariakas81#9664

> Upvote - Stelarius#9171

> Upvote - 223997790789828610

> Upvote - bbWalole#8888

> Upvote - Kamátikos#9012

> Upvote - Beans#0464

> Upvote - Kalistad#1728

> Upvote - Rikkisa#2639

> Upvote - Cryover#9281

> Upvote - SetArk#9658

> Upvote - ApoApostolov#4622

> Upvote - thorni#4664

> Upvote - Makke#8524

> Upvote - Joonasm#2159

> Upvote - Modnar#2707

> Upvote - Tercept#0001

> Upvote - Dragon#2777

> Upvote - ShingekiSkunk#2922

> Upvote - ShadeNinja#6273

> Upvote - Gylean#9846

> Upvote - dasuberchin#7657

> Upvote - Jenkins#2462

> Upvote - logEekumenAgination#9568

> Upvote - MG5man#2172

> Upvote - turnc0at#0683

> Upvote - Digi#5150

> Upvote - Goat#2989

> Upvote - magsona!#6969

> Upvote - rare form#0001

> Upvote - Arctur#4946

> Upvote - Xijiks#5210

> Upvote - silva367#5329

> Upvote - Mr. Rossi#6187

> Upvote - Red Reign#5128

> Upvote - Tim#6226

> Upvote - Joe Moe#7612

> Upvote - Anthyrst#5317

> Upvote - TomBomb#4287

> Upvote - BFM | Bom#9805

> Upvote - Lxran#2292

> Upvote - DharmaLeader#1934

> Upvote - DemonPookie#4793

> Upvote - gsl#9270

> Upvote - Grandpa#9957

> Upvote - Innocenti#1455

> Upvote - Ikaguia#2965

> Upvote - Manticore#5668

> Upvote - quantumrazorback#3586

> Upvote - TheRealBen#5242

> Upvote - Reevo55#7737

> Upvote - Nekro Philadelphia#2491

> Upvote - Reck#4887

> Upvote - sebastianmx2#1999

> Upvote - Sub#6366

Votes: +58 / -0

**Comment by apoapostolov** [comment]
Further improvement, similar to how art repo is handled:
- Website where Plutonium users can propose and vote (to weed out false positives or spam) and report (removed, etc.) videos
- Tag and directory system that allows users to assign tags like Dungeon, Battle, Atmospheric, Goblin, etc. that can be searchable afterwards.

**Comment by crawltracker** [comment]
Note - Modnar#2707

https://github.com/temportalflux/MusicAssist , consider closing as duplicate feature exists (and ... apparently will even support Spotify) <a:think3d:551466619583594516>
