### ISSUE TITLE
5ET-054 Allow searching for filters, e.g. https://cdn.discordapp.com/attachments/470673367628906496/556619581251125248/unknown.png

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#54]
**Feature Request:** Allow searching for filters, e.g. https://cdn.discordapp.com/attachments/470673367628906496/556619581251125248/unknown.png
**5eTools or BetteR20?** 5eTools

- LordDusk#0001

> Upvote - KidMessiah#8501

> Upvote - InstantZzz#6286

> Upvote - Metacomet10#3669

> Downvote - Gathis#6628

> Upvote - Liefrigg#3476

> Upvote - curiosthedeadcat#0480

> Upvote - Modnar#2707

> Upvote - SigilBlue#6700

> Upvote - badooga#8108

> Upvote - Aevilok#6979

> Upvote - Kicktar#0233

> Upvote - HaLwAsA#5109

> Upvote - joshjosh100#6666

Votes: +12 / -1

**Comment by 5ecrawlreporter** [comment]
Note - Modnar#2707

- see 5eT-017 (5etools/tracker#17); as there is some cross over; TL;DR - allow filter terms to be typed in the topic search field per topic - with discord like help on the search topic 
https://media.discordapp.net/attachments/470673367628906496/629326492182118431/unknown.png?width=258&height=265
example: (when in spells)
> **Search**: **level**= 2  **class**=Wizard would result in all 2nd level spells from wizard spell list.

**Comment by crawltracker** [comment]
Note - Giddy#0001
