### ISSUE TITLE
plutonium race importer: incorrect settings for Hellish Rebuke via Tiefling Infernal Legacy

### ISSUE THREAD

**Issue by foresto** [5etools/tracker#635]
Hellish Rebuke, when used via Tiefling's Infernal Legacy, is supposed to be cast at 2nd level using Charisma as the spellcasting ability. Plutonium's race importer ignores that rule when creating the spell on the 5e sheet, causing it to be cast at 1st level using the class spellcasting ability instead.

Plutonium 1.16.2
Foundry 0.7.8

**Comment by TheGiddyLimit** [comment]
ceci n'est pas un issue tracker
