### ISSUE TITLE
5ET-529 (Homebrew) A reload button for making deleting and re-adding sources easier

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#643]
**Feature Request:** (Homebrew) A reload button for making deleting and re-adding sources easier.

**Extra Information**
**Who would use it?** People who use homebrew and *especially* converters who wants to troubleshoot their files.
**How would it work?** A `refresh` icon next to the trash can icon that does either of the following: 
a) Delete and re-add the latest version of the brew from the repo.
b) If the file is local, save file path of the local file upon initial addition in cookies and when clicked, try to find a brew of the same file path, and if it exists, delete and re-add the file.
If it turns into a check mark or X after the operation that would be great too! Also, a larger one for trying to update all brews would be appreciated.
**Why should this be added?** Going into the Homebrew Manager, deleting the brew, clicking Upload File, navigating to the file, and adding it gets tedious after the first 15 times when you are testing something. I think brew auto-update is on the way iirc, but this is still useful I believe. There might be some privacy/security concerns about sharing your file directories in cookies in a state file, but you only generate it when you want to give away your privacy so there's that.

- Lxran#2292

> Indifferent - The Pi Guy#3953

> Upvote - Lxran#2292

> Indifferent - 155435500159631360

> Indifferent - deraviin#9963

> Upvote - spap#9812

> Upvote - SigilBlue#6700

> Upvote - ShingekiSkunk#2922

> Indifferent - Insaiyan7#6364

> Upvote - Frost2779#4895

> Upvote - 98476238531756032

> Upvote - Uelman#1630

> Upvote - gloom#3169

> Upvote - JLtheking#0799

> Upvote - FairUnknown#5130

> Upvote - Daldo#3259

> Downvote - 554780101129142290

> Upvote - Ikaguia#2965

> Indifferent - Thomas Edgerton#8370

> Indifferent - 353572001019068448

> Upvote - DaJur#0395

> Upvote - guKing#6803

> Upvote - Ebonhawk#3829

> Indifferent - 749807256866127973

> Indifferent - Ojciec Mateusz#5981

> Upvote - Hajo#6436

> Upvote - OokOok#1521

> Upvote - Craig#9789

> Upvote - Georgi#1491

> Upvote - hawkeye323#0753

> Indifferent - ShadowedMage#9457

> Upvote - Eaminwe#9245

> Upvote - Pluto Anatole#4332

> Note - Lxran#2292
> 
> A little thing I have noticed, when changes to the site and by extension, homebrew schema happen, lots of people flock to the issues channel (and sometimes mistakenly other channels), as their pages are broken due to out of date homebrew in their localstorage. This, and by extension, 5ET-010 (5etools/tracker#10) "Homebrew Auto Update" would reduce the amount of people in need of help.

> Upvote - revilowaldow#0001

> Upvote - 522909673859579975

> Upvote - AulesHand#3617

> Upvote - DXHHH101#1001

> Note - DXHHH101#1001
> 
> **Feature Request:** Option to overwrite homebrew with the same name
> 
> **Extra Information** If I upload something called "The Beyond" and then upload it again (to fix a typo or something), I have to find it in my list, hit delete, confirm it, and then upload the new file. It'd be nice if I could just upload it and have it overwrite (delete the old and add the new) it automatically.
> **Who would use it?** Homebrewers who make tiny adjustments at a time to see visual changes/quick typo fixes.
> **How would it work?** Add a confirmation when uploading homebrew that has the same `"full"` name as something already uploaded. "This already exists, want to overwrite it?"
> Could also have a checkbox on the page too, "always overwrite" to remove the confirmation and just always overwrite homebrew with the same name
> **Why should this be added?** Uploading the same file over and over again to check/fix minute details like table width, links to items/races/etc, and typos is annoying when you have 20+ homebrew uploaded as you have to root through the list every time to find the right one to delete.

> Indifferent - spap#9812

> Indifferent - Nihiraz#3533

> Indifferent - Shilques#8027

> Note - IssueCrawler#1030
> 
> Merged `5ET-816 (5etools/tracker#0)` into `5ET-529 (5etools/tracker#643)`

> Upvote - kierann#6245

> Upvote - modnar#9949

Votes: +28 / -1 / ±9

**Comment by trunzoc** [comment]
this would be so good

**Comment by crawltracker** [comment]
Note - Lxran#2292

A little thing I have noticed, when changes to the site and by extension, homebrew schema happen, lots of people flock to the issues channel (and sometimes mistakenly other channels), as their pages are broken due to out of date homebrew in their localstorage. This, and by extension, 5ET-010 (5etools/tracker#10) "Homebrew Auto Update" would reduce the amount of people in need of help.

**Comment by crawltracker** [comment]
Note - IssueCrawler#1030

Merged `5ET-816 (5etools/tracker#0)` into `5ET-529 (5etools/tracker#643)`

**Comment by crawltracker** [comment]
Note - Giddy#0001

Resolved - Implemented
