### ISSUE TITLE
5ET-575 Site images converted to webp

### ISSUE THREAD

**Issue by crawltracker** [5etools/tracker#692]
**Feature Request:** Site images converted to webp

**Extra Information**
**Who would use it?** everyone, but.. they'd not know it.
**How would it work?** Convert all the images to webp and update code to match new file types; and make the images pack smol
**Why should this be added?** Cloudflare already does this so its not really necessary for live, but might help with local or individual installs for speed/smaller footprint

(ie. very low - I'm very board and looking for a RegEx/ffmpeg thing to script while I'm watching NetFlix. 

People will be mad if its done. as their image links (including the art Repo's will break)

- modnar#9949

> Note - MrVauxs#8622
> 
> Additionally:
> People will be mad if its done. As they will keep getting webp images when trying to download the images off the site.

> Upvote - spap#9812

> Upvote - Tercept#0066

> Upvote - ShingekiSkunk#2922

> Upvote - 155435500159631360

> Downvote - SigilBlue#6700

> Indifferent - 353572001019068448

> Downvote - Sock#2082

> Downvote - Thandulfan#0087

> Upvote - pickers101#2916

> Upvote - Cloudancer#4730

> Indifferent - 749807256866127973

> Upvote - Ikaguia#2965

> Upvote - arcanist#4317

> Downvote - Dorgrim#2429

> Downvote - SmolTreeSnek#7525

> Indifferent - Uelman#1630

> Upvote - BaumMeister#8539

> Upvote - SpiceBandit#5640

> Upvote - razvantr98#3397

> Upvote - svtkachenko#9318

> Upvote - modnar#9949

> Upvote - revilowaldow#0001

> Downvote - foreveryone#6438

> Downvote - Konahrik13#3572

> Upvote - 791425355398905876

> Downvote - ToadDan#3785

> Downvote - Zero Man#1845

> Upvote - prostheticHead#2993

> Upvote - ondra#3063

> Upvote - Melithian#5390

> Upvote - GrayDiamond#2021

> Upvote - Sgt_Wolf#1152

> Upvote - ariakas81#9664

> Upvote - Myndranius#3354

> Upvote - bigeldoth#9057

> Upvote - Grass#6297

> Upvote - DM Keith#2042

> Indifferent - SetArk#9658

> Downvote - Twilight Sparkle#9786

> Upvote - dimi#5469

> Upvote - 771212422773604352

> Upvote - DaJur#0395

> Downvote - beeps#4403

> Upvote - Surge#5715

> Downvote - alexonyx64#5213

> Downvote - Danbog#2054

> Upvote - princeofmar5#7900

> Downvote - Dachimotsu#1054

> Indifferent - elia2904#8398

> Indifferent - Szefo09#1005

> Upvote - 218405183175000074

> Downvote - fieryrayne#6419

> Upvote - Lxran#2292

> Upvote - bill#0265

> Downvote - ClashPoint#5484

> Downvote - Ike#1337

> Upvote - OokOok#1521

> Upvote - Almightycricket#7252

> Upvote - deraviin#9963

> Downvote - PandaPugBook#1178

> Upvote - Juanfrank#9519

> Downvote - 363099420381675520

> Upvote - Joey Joël#1203

> Downvote - Night_Wolf55#5158

> Upvote - Georgi#1491

> Downvote - 335163277426556928

> Downvote - Yuuki#5975

> Downvote - Ninjas#0595

> Downvote - LadySaga#8441

> Upvote - ZachMyers3#1146

> Upvote - mucira#1532

> Downvote - Tovar#1235

> Downvote - Dungeon_Master_Moe#0915

> Upvote - VAD#3906

> Upvote - ShadowedMage#9457

> Upvote - X-420#1906

> Downvote - zorgrath#4256

> Upvote - Paulomat#9140

> Upvote - OfficerHalf#2990

> Upvote - Arth#2710

> Note - modnar#9949
> 
> <@!383507911160233985> has already converted the images if we want to use a different set. 
> https://drive.google.com/file/d/1neaUUg87ZyIG4I5ZSfVjsgId0AJC2b0j/view?usp=sharing

> Upvote - Max Bureka#4525

> Upvote - BuyMyMojo#0308

> Upvote - marshall#5180

> Upvote - Sir Kaven#6143

> Upvote - Core#9641

> Upvote - BostonRay#9757

> Downvote - Bard-A-Bear#1924

> Indifferent - Lisu#4516

Votes: +53 / -28 / ±7

**Comment by Mauarus** [comment]
Please don't. For context, here is my original comment on Discord:

Hi, one of the things I like the most about 5e.tools is that I can send books and adventures I own to my Kindle, to read whenever I can. It works with all the content so far, but now with the Adventure Icewind Dale. I have identified a potential cause: some images are in WEBP format and Amazon does not like that, so it ignores the entire document. I've tried CTRL+C / V to Google Docs, and those images also cause trouble there. Deleting them worked, but it costed me some time. Any comments on that image format, why just "Icewind Dale" and is there anything to do about it?

Someone also said: "It is simply a more efficient and way smaller file format".

**Comment by crawltracker** [comment]
Note - modnar#9949

<@!383507911160233985> has already converted the images if we want to use a different set. 
https://drive.google.com/file/d/1neaUUg87ZyIG4I5ZSfVjsgId0AJC2b0j/view?usp=sharing

**Comment by crawltracker** [comment]
Note - giddy_#0

Resolved - Implemented
